# Filtrar la data para Mantenimiento predictivo (Predictive maintenance) = Time To Event Model


* Filtraremos por discos duros que fallaron en el año dado (tanto por conveniencia como por tamaño del archivo).

* Más adelante usaremos estos datos para crear un modelo de regresión: tiempo de falla.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\rolft\Documents\UAI\UAI_2020\AP_git\me_code\Prueba_2\data\harddrive.csv')
print(df.shape)
df.head()

(3179295, 95)

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2016-01-01,MJ0351YNG9Z0XA,Hitachi HDS5C3030ALA630,1.482490e-311,0,100,0,135.0,108.0,143,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01,Z305B2QN,ST4000DM000,1.976651e-311,0,113,54551400,NaN,NaN,96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,MJ0351YNG9Z7LA,Hitachi HDS5C3030ALA630,1.482490e-311,0,100,0,136.0,104.0,124,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01,MJ0351YNGABYAA,Hitachi HDS5C3030ALA630,1.482490e-311,0,100,0,136.0,104.0,137,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01,WD-WMC4N2899475,WDC WD30EFRX,1.482490e-311,0,200,0,NaN,NaN,175,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe(include='all')

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
count,3179295,3179295,3179295,3.179295e+06,3.179295e+06,3.179295e+06,3.179295e+06,1.259118e+06,1.259118e+06,3.179295e+06,...,2835.0,2.835000e+03,2835.000000,2.835000e+03,2835.000000,2.835000e+03,7935.000000,7935.0,0.0,0.0
unique,50,65993,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-04-01,JK11A8B9HZTN8R,ST4000DM000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,125904,52,1681473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,1.849552e-311,6.762506e-05,1.121816e+02,6.856751e+07,1.287652e+02,7.491735e+01,1.052967e+02,...,1.0,1.020068e+08,6.412698,1.948479e+08,19.822222,8.940533e+07,116.131065,0.0,NaN,NaN
std,NaN,NaN,NaN,0.000000e+00,8.223169e-03,1.871325e+01,8.002785e+07,2.488450e+01,4.557482e+01,1.870145e+01,...,0.0,7.223558e+07,22.510855,1.462246e+08,38.854298,6.703960e+07,36.784042,0.0,NaN,NaN
min,NaN,NaN,NaN,3.953828e-313,0.000000e+00,3.300000e+01,0.000000e+00,1.000000e+02,0.000000e+00,7.000000e+01,...,1.0,2.452300e+04,1.000000,6.600000e+01,1.000000,0.000000e+00,100.000000,0.0,NaN,NaN
25%,NaN,NaN,NaN,1.976651e-311,0.000000e+00,1.000000e+02,0.000000e+00,1.310000e+02,0.000000e+00,9.400000e+01,...,1.0,1.462176e+07,1.000000,1.722997e+07,1.000000,7.881220e+06,100.000000,0.0,NaN,NaN
50%,NaN,NaN,NaN,1.976651e-311,0.000000e+00,1.120000e+02,2.984580e+07,1.330000e+02,1.000000e+02,9.800000e+01,...,1.0,1.412617e+08,1.000000,2.741461e+08,1.000000,1.254753e+08,100.000000,0.0,NaN,NaN
75%,NaN,NaN,NaN,1.976651e-311,0.000000e+00,1.170000e+02,1.343214e+08,1.340000e+02,1.040000e+02,1.140000e+02,...,1.0,1.667429e+08,1.000000,3.278856e+08,1.000000,1.500801e+08,100.000000,0.0,NaN,NaN
max,NaN,NaN,NaN,3.953298e-311,1.000000e+00,2.000000e+02,1.916485e+09,2.520000e+02,1.960000e+02,2.530000e+02,...,1.0,1.992453e+08,100.000000,3.862757e+08,100.000000,1.782887e+08,200.000000,0.0,NaN,NaN

In [3]:
# drop constant columns
df = df.loc[:, ~df.isnull().all()]
print(df.shape)

(3179295, 91)

In [5]:
# number of hdd
print("number of hdd:", df['serial_number'].value_counts().shape) 

# number of different types of harddrives
print("number of different harddrives", df['model'].value_counts().shape)

number of hdd: (65993,)
number of different harddrives (69,)

# Conservaremos solo los discos duros (HDDs) que fallaron

* Idealmente, usaríamos varios años de datos para más modelos y rango. Hay un gran sesgo aquí cuando no incluimos discos duros que no fallaron.

    * También perdemos la capacidad de identificar discos duros (HDDs) verdaderamente "saludables".

In [5]:
#.loc indexa a traves de la selección tipo array
failed_hdds = df.loc[df.failure==1]["serial_number"]
len(failed_hdds)
failed_hdds.describe()

count          214
unique         205
top       W3006E5B
freq             2
Name: serial_number, dtype: object

Se encontró un item que fallo dos veces coon el mismo ID, se indigará este item para ver si se utilizó su id de nuevo.

In [17]:
#& df.serial_number=='WD-WCC4MKDL77ZK'
caso_rraro=df.loc[df.failure==1 ]#["serial_number"]
caso_rraro=caso_rraro.loc[caso_rraro.serial_number=='WD-WCC4MKDL77ZK']
caso_rraro#.describe()

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_242_normalized,smart_242_raw,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw
30285,2016-01-01,WD-WCC4MKDL77ZK,WDC WD20EFRX,9.883284e-312,1,200,0,NaN,NaN,100,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87830,2016-01-01,WD-WCC4MKDL77ZK,WDC WD20EFRX,9.883284e-312,1,200,0,NaN,NaN,100,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Se aprecia que este Item fallo dos veces el mismo dia, es completamente un dato duplicado, por lo cual se procede a eliminar.

In [26]:
item_A=df.loc[df.serial_number=='WD-WCC4MKDL77ZK']
item_A

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
30285,2016-01-01,WD-WCC4MKDL77ZK,WDC WD20EFRX,9.883284e-312,1,200,0,NaN,NaN,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87830,2016-01-01,WD-WCC4MKDL77ZK,WDC WD20EFRX,9.883284e-312,1,200,0,NaN,NaN,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# eliminamos la data que esta repetida
df=df.drop([87830],axis=0)

No posee historia osea que falló en T=1, en el primer instante que aprece en la data

In [6]:
df = df.loc[df["serial_number"].isin(failed_hdds)]
df.shape

(5489, 91)

In [7]:
df.to_csv("data_fail.csv", index = False, sep=',', encoding='utf-8')

# Trabajar con data_fail

In [ ]:
df = pd.read_csv(r'data\data_fail.csv')
print(df.shape)
df.head()

In [32]:
#Crear una columna con el dia en que muere el articulo
df["end_date"] = df.groupby("serial_number")["date"].transform("max")

C:\Users\rolft\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [14]:
df

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_242_raw,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,end_date
376,2016-01-01,Z300ZST1,ST4000DM000,1.976651e-311,0,120,240872800,NaN,NaN,91,...,9.784107e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-17
1657,2016-01-01,9VY8TCAV,ST3160318AS,7.907120e-313,0,111,38605541,NaN,NaN,97,...,2.076417e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-09
1895,2016-01-01,W300BG0H,ST4000DM000,1.976651e-311,0,118,190147064,NaN,NaN,91,...,6.394443e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-18
2900,2016-01-01,W300J6FX,ST4000DM000,1.976651e-311,0,115,85258376,NaN,NaN,92,...,6.040397e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-09
3204,2016-01-01,Z3014A4S,ST4000DM000,1.976651e-311,0,116,101976792,NaN,NaN,91,...,1.019657e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-10
3615,2016-01-01,Z4D045CF,ST6000DX000,2.964974e-311,0,116,101694695,NaN,NaN,88,...,1.176377e-310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-05
3721,2016-01-01,Z4D04BH9,ST6000DX000,2.964974e-311,0,115,93122944,NaN,NaN,89,...,3.324008e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-05
3784,2016-01-01,Z3013TQV,ST4000DM000,1.976651e-311,0,108,20319352,NaN,NaN,91,...,1.042785e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-11
3809,2016-01-01,WD-WX11D84JN1EP,WDC WD60EFRX,2.964974e-311,0,200,0,NaN,NaN,202,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-05
3909,2016-01-01,W0Q26EE1,ST320LT007,1.581370e-312,0,118,177471776,NaN,NaN,98,...,8.233935e-315,1.0,13579666.0,1.0,26548746.0,1.0,12207968.0,100.0,0.0,2016-01-21
3959,2016-01-01,Z300PM99,ST4000DM000,1.976651e-311,0,118,187666096,NaN,NaN,92,...,1.167141e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-06
4064,2016-01-01,Z300GYM0,ST4000DM000,1.976651e-311,0,118,196694488,NaN,NaN,91,...,4.862980e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-01
4220,2016-01-01,JK1105B8J10GXX,Hitachi HDS722020ALA330,9.883284e-312,0,97,393217,100.0,0.0,119,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-13
5240,2016-01-01,WD-WCC4M3TTXF1Y,WDC WD20EFRX,9.883284e-312,0,200,247,NaN,NaN,100,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-03
5714,2016-01-01,Z3015CR3,ST4000DM000,1.976651e-311,0,106,11315960,NaN,NaN,91,...,1.083224e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-06
5824,2016-01-01,WD-WMC4N0727496,WDC WD30EFRX,1.482490e-311,0,200,0,NaN,NaN,100,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-25
5830,2016-01-01,WD-WMAV3K823369,WDC WD1600AAJB,7.907120e-313,0,200,0,NaN,NaN,139,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-13
6029,2016-01-01,Z3015C7D,ST4000DM000,1.976651e-311,0,119,215630552,NaN,NaN,92,...,1.041904e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-18
6393,2016-01-01,W300SSCN,ST4000DM000,1.976651e-311,0,117,163030352,NaN,NaN,99,...,1.120693e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-19
6520,2016-01-01,Z300GZ7X,ST4000DM000,1.976651e-311,0,114,83503256,NaN,NaN,92,...,6.812561e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-11
7677,2016-01-01,W300J9JA,ST4000DM000,1.976651e-311,0,117,135719336,NaN,NaN,91,...,1.030553e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-01
7912,2016-01-01,Z300XBVK,ST4000DM000,1.976651e-311,0,115,97291736,NaN,NaN,92,...,2.531626e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-11
8007,2016-01-01,Z300X7EZ,ST4000DM000,1.976651e-311,0,115,87974488,NaN,NaN,92,...,1.099540e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-06
8289,2016-01-01,W300B34S,ST4000DM000,1.976651e-311,0,119,223997848,NaN,NaN,92,...,7.967812e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-06
8385,2016-01-01,S301146W,ST4000DM000,1.976651e-311,0,112,46316008,NaN,NaN,97,...,3.348736e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-02
9036,2016-01-01,JK1105B8GA6AYX,Hitachi HDS722020ALA330,9.883284e-312,0,100,65536,100.0,0.0,115,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-01-05
9477,2016-01-01,S300Z46R,ST4000DM000,1.976651e-311,0,116,115614024,NaN,NaN,97,...,3.633167e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-15
9874,2016-01-01,Z3026YZN,ST4000DM000,1.976651e-311,0,115,99616608,NaN,NaN,93,...,6.891453e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-06
10711,2016-01-01,W300BT0J,ST4000DM000,1.976651e-311,0,112,46846400,NaN,NaN,92,...,1.389048e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-15
11131,2016-01-01,S300XR31,ST4000DM000,1.976651e-311,0,114,64918032,NaN,NaN,99,...,6.737175e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3005981,2016-04-27,W0Q6GWHX,ST320LT007,1.581370e-312,0,111,41727272,NaN,NaN,98,...,7.338110e-315,1.0,28481099.0,1.0,56398869.0,1.0,25661401.0,100.0,0.0,2016-04-28
3007719,2016-04-27,Z302A13D,ST4000DM000,1.976651e-311,0,111,36150000,NaN,NaN,97,...,1.111404e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-29
3007758,2016-04-27,Z300X1K0,ST4000DM000,1.976651e-311,1,114,66963256,NaN,NaN,91,...,5.850361e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-27
3010185,2016-04-27,JK11A8B9J90WMF,Hitachi HDS722020ALA330,9.883284e-312,0,100,0,100.0,0.0,118,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-29
3010423,2016-04-27,WD-WCAMD1671734,WDC WD800BB,3.953828e-313,1,200,0,NaN,NaN,167,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-27
3014495,2016-04-27,Z304R6NY,ST4000DM000,1.976651e-311,0,115,94799168,NaN,NaN,97,...,7.319151e-315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3019379,2016-04-27,Z30250YD,ST4000DM000,1.976651e-311,0,119,205233776,NaN,NaN,98,...,2.006650e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3019599,2016-04-27,W0Q6KWV8,ST320LT007,1.581370e-312,0,114,71076440,NaN,NaN,98,...,1.410280e-314,1.0,183869206.0,1.0,358327380.0,1.0,164103254.0,100.0,0.0,2016-04-28
3021607,2016-04-27,Z300T6ZF,ST4000DM000,1.976651e-311,1,113,52426176,NaN,NaN,91,...,3.291289e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-27
3036033,2016-04-27,S300XP36,ST4000DM000,1.976651e-311,0,111,39909736,NaN,NaN,98,...,7.901410e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3037837,2016-04-27,JK1101B9JPVHXF,Hitachi HDS722020ALA330,9.883284e-312,1,100,0,131.0,108.0,114,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-27
3041273,2016-04-27,W300T2RC,ST4000DM000,1.976651e-311,0,117,166408096,NaN,NaN,91,...,5.082578e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3043089,2016-04-27,W300CWLM,ST4000DM000,1.976651e-311,1,117,166288704,NaN,NaN,92,...,7.018699e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-27
3063668,2016-04-28,Z300XD1D,ST4000DM000,1.976651e-311,1,117,157113744,NaN,NaN,91,...,1.178391e-312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3064072,2016-04-28,W0Q7G3WK,ST320LT007,1.581370e-312,1,111,34959712,NaN,NaN,98,...,1.875101e-314,1.0,112676214.0,1.0,210661075.0,1.0,99013941.0,100.0,0.0,2016-04-28
3064433,2016-04-28,W0Q7G3JM,ST320LT007,1.581370e-312,1,117,156756280,NaN,NaN,98,...,7.924656e-315,1.0,11449236.0,1.0,22924469.0,1.0,10324409.0,100.0,0.0,2016-04-28
3065905,2016-04-28,S300XRCA,ST4000DM000,1.976651e-311,1,114,63639792,NaN,NaN,98,...,5.148116e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3066002,2016-04-28,W0Q7D8BK,ST320LT007,1.581370e-312,1,118,171725696,NaN,NaN,98,...,3.940444e-315,1.0,181975578.0,1.0,356526577.0,1.0,162983113.0,100.0,0.0,2016-04-28
3067544,2016-04-28,W0Q7G36S,ST320LT007,1.581370e-312,1,116,112130656,NaN,NaN,98,...,5.036401e-315,1.0,169686044.0,1.0,331807798.0,1.0,151444174.0,100.0,0.0,2016-04-28
3067625,2016-04-28,Z3025KHS,ST4000DM000,1.976651e-311,1,105,138096466,NaN,NaN,98,...,2.035433e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3070640,2016-04-28,W0Q6GWHX,ST320LT007,1.581370e-312,1,116,114305528,NaN,NaN,98,...,1.133554e-314,1.0,28659559.0,1.0,56756206.0,1.0,25825009.0,100.0,0.0,2016-04-28
3072374,2016-04-28,Z302A13D,ST4000DM000,1.976651e-311,0,117,142694864,NaN,NaN,97,...,1.112559e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-29
3074838,2016-04-28,JK11A8B9J90WMF,Hitachi HDS722020ALA330,9.883284e-312,0,100,0,100.0,0.0,118,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-29
3079138,2016-04-28,Z304R6NY,ST4000DM000,1.976651e-311,1,111,39078096,NaN,NaN,97,...,7.351195e-315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3084009,2016-04-28,Z30250YD,ST4000DM000,1.976651e-311,1,117,118145096,NaN,NaN,98,...,2.008446e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3084227,2016-04-28,W0Q6KWV8,ST320LT007,1.581370e-312,1,117,147958432,NaN,NaN,98,...,3.733211e-315,1.0,184044804.0,1.0,358677046.0,1.0,164262565.0,100.0,0.0,2016-04-28
3100634,2016-04-28,S300XP36,ST4000DM000,1.976651e-311,1,117,146527232,NaN,NaN,98,...,7.902839e-314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3105860,2016-04-28,W300T2RC,ST4000DM000,1.976651e-311,1,117,144495808,NaN,NaN,91,...,5.084032e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-28
3136939,2016-04-29,Z302A13D,ST4000DM000,1.976651e-311,1,119,223384952,NaN,NaN,97,...,1.112712e-313,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-29
3139403,2016-04-29,JK11A8B9J90WMF,Hitachi HDS722020ALA330,9.883284e-312,1,100,0,100.0,0.0,118,...,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-04-29

In [15]:
df["end_date"] = pd.to_datetime(df["end_date"])
df["date"] = pd.to_datetime(df["date"])

In [16]:
df["date_diff"] = df["end_date"] - df["date"]
df["date_diff"].describe()

count                       5490
mean     49 days 09:18:25.573770
std      44 days 09:17:21.395230
min              0 days 00:00:00
25%              7 days 00:00:00
50%             21 days 00:00:00
75%             95 days 00:00:00
max            119 days 00:00:00
Name: date_diff, dtype: object

In [18]:
df["smart_9_raw"].describe()

count     5490.000000
mean     19560.998725
std      12483.140262
min         14.000000
25%       9535.750000
50%      19234.500000
75%      25783.000000
max      67744.000000
Name: smart_9_raw, dtype: float64

* Parece que las fallas tienen una distribución extraña. tal vez estén agrupados alrededor del inicio / final de un año / trimestre.

* NOTE que dejar la fecha en la fecha dará lugar a una fuga en nuestro modelo si no tenemos cuidado (más adelante en el [mismo] año = mayor probabilidad de falla!

# replace string/object with number
df["date_diff"] = df["date_diff"].dt.days
df.drop(["end_date","failure"],axis=1,inplace=True)
print(df.shape)

# replace string/object with number
df["date_diff"] = df["date_diff"].dt.days
df.drop(["end_date","failure"],axis=1,inplace=True)
print(df.shape)

In [ ]:
df.to_dense().to_csv("submission.csv", index = False, sep=',', encoding='utf-8')